language: node_js
sudo: required
node_js:
  - "stable"
  - '6'
  - '5'
  - '4'
before_install: npm install -g grunt-cli initialize
install: npm install
before_script: grunt build
script: grunt travis

  
